swagger: "2.0"
info:
  title: "Swagger Example"
  description: >
    This is an example Koa API.
  version: "1.0.0"
host: "localhost:3000"
schemes:
  - "http"

paths:
/health:
    get:
    summary: "Check the status of the service"
    description: "If the service is up and running correctly the response will be 'UP'"
    consumes:
        - "application/json"
    produces:
        - "application/json"
    responses:
        200:
        description: "Service is up and healthy"
        schema:
            $ref: "#/definitions/Health"
        500:
        $ref: '#/responses/500'

responses:
500:
    description: Internal Server Error
    schema:
    $ref: '#/definitions/Error'

definitions:
Health:
    type: "object"
    properties:
    status:
        type: "string"
        enum:
        - "UP"
        - "DOWN"
  
  